/* Never Have I Ever (standard + 18+) and Spicy Would You Rather.
   All built on the shared duo-game factory. */
import { makeDuoGame } from './prompted.js';

/* ---------------- Never Have I Ever — standard ---------------- */
const NHIE_STD = [
  '…fallen asleep on a video call with someone.', '…written a song or poem about someone.',
  '…had a crush on a friend\'s sibling.', '…googled "how to know if someone likes me".',
  '…practiced a conversation in the mirror.', '…replayed a first kiss in my head this week.',
  '…cooked a meal to impress someone.', '…worn someone else\'s hoodie until it smelled like them.',
  '…danced alone to "our song".', '…saved a screenshot of a cute message.',
  '…laughed so hard with someone I cried.', '…written a text and deleted it ten times.',
  '…stalked someone\'s profile at 2am.', '…said "I\'m fine" when I absolutely was not.',
  '…kissed someone under the rain.', '…held hands in a movie theater.',
  '…planned a future daydream with someone in it.', '…skipped work or class to spend a day with someone.',
  '…sang karaoke to impress someone.', '…tried to cook their favorite dish and failed.',
  '…cried at a rom-com this year.', '…kept a memento from a first date.',
  '…made a playlist for someone.', '…waited hours just to see someone for five minutes.',
  '…fallen for my best friend.', '…said "I love you" first.',
  '…had a date end in a food fight.', '…gotten lost with someone and loved it.',
  '…watched the stars with someone special.', '…been someone\'s first kiss.',
  '…fallen asleep smiling after a date.', '…named a pet after someone I loved.',
  '…smiled at my phone like a fool in public.', '…danced in the kitchen at midnight.',
  '…passed a folded note in class that just said "look behind you".',
  '…practiced a casual "hey" in the mirror for ten minutes.',
  '…taken the long way home to walk past a crush\'s street.',
  '…pretended to love a band just because a crush did.',
  '…joined a club only because someone cute was in it.',
  '…sent a friend on a secret mission to ask if someone was single.',
  '…memorized a crush\'s schedule without even trying.',
  '…written a crush\'s name with my surname after it, just to see.',
  '…doodled tiny hearts around someone\'s name in a notebook.',
  '…waved back at someone who was waving at the person behind me.',
  '…tripped over absolutely nothing while walking past a crush.',
  '…laughed at a joke I didn\'t understand at all.',
  '…sat through a three-hour movie just because a crush was in it.',
  '…read an entire book series to have something to talk about.',
  '…kept a cheesy love song as my secret anthem.',
  '…rehearsed a confession for weeks and then chickened out.',
  '…had a friend confess my feelings for me and immediately regretted it.',
  '…been set up on a blind date by an overenthusiastic aunt.',
  '…nodded along to a show I had never watched to seem interesting.',
  '…lied about knowing how to slow dance and got called out on the spot.',
  '…pretended to be a coffee person on a first date.',
  '…applauded a proposal in a cinema that wasn\'t ours.',
  '…changed my music taste out loud just to impress someone.',
  '…asked my friends to rate a selfie before sending it.',
  '…taken fifty selfies to find one worth sending.',
  '…typed "I miss you" and deleted it three times before sending.',
  '…left someone on read for two days to seem mysterious.',
  '…reread an old conversation until 3 a.m.',
  '…screenshot a sweet message to save it forever.',
  '…made our first-date photo my profile picture everywhere.',
  '…set a notification tone just for one person.',
  '…given a contact name a heart emoji and then changed it back out of nerves.',
  '…typed a whole paragraph and replaced it with "lol".',
  '…accidentally liked a photo from three years ago while lurking.',
  '…stared at the typing bubble like it was a football match.',
  '…sent a text to the wrong person and panicked.',
  '…autocorrect betrayed me in an important message.',
  '…sent a voice memo and immediately wanted to unsend it.',
  '…practiced saying "goodnight" with three different emojis.',
  '…waited a whole day to reply to one emoji on purpose.',
  '…fallen for someone purely over texting before ever meeting.',
  '…had a full conversation using only emojis.',
  '…sent a song link instead of saying how I felt.',
  '…typed "nothing" when I was clearly thinking about them.',
  '…set a 6 a.m. alarm just to say good morning first.',
  '…kept a chat open on a second screen during work.',
  '…grinned at my phone in the middle of a movie and got shushed.',
  '…texted "I\'m not mad" while absolutely being mad.',
  '…sent a photo of my dinner to someone who didn\'t ask.',
  '…kept a voicemail just to hear the voice again.',
  '…replayed a voice note five times before answering.',
  '…fallen asleep mid-text and woken up to my own unfinished message.',
  '…spellchecked a flirty message like it was a job application.',
  '…debated the punctuation of a single word for ten minutes.',
  '…sent "haha" when I was actually blushing.',
  '…staged a candid photo and taken twenty attempts.',
  '…booked a flight before telling anyone I was going.',
  '…counted time zones like a pilot.',
  '…decorated a wall with printed photos of us side by side.',
  '…kept a countdown for a visit on my phone.',
  '…cried at an airport and pretended it was allergies.',
  '…waved at a laptop camera like an absolute goofball.',
  '…had a dinner date over video call with candles on both ends.',
  '…resynced movie play buttons more than five times.',
  '…watched the sunrise on a call because one of us couldn\'t sleep.',
  '…said goodnight over chat and then talked for two more hours.',
  '…flown for a first date with someone I met online.',
  '…surprised someone at the airport with a ridiculous sign.',
  '…jogged through arrivals with flowers held high.',
  '…kept their hoodie on my pillow just for the smell.',
  '…hugged a pillow and pretended it was a particular person.',
  '…worn my partner\'s hoodie like armor on a hard day.',
  '…planned a visit around a food I wanted them to try.',
  '…mailed a letter with a lipstick kiss pressed at the bottom.',
  '…mailed a care package stuffed with inside jokes.',
  '…hidden notes around my house for a visit I hadn\'t booked yet.',
  '…written "I miss you" in steam on the bathroom mirror.',
  '…learned their grandmother\'s recipe over video call.',
  '…learned a few phrases of their language just to flirt.',
  '…translated a pet name badly and kept the funny result.',
  '…added their city to my weather app and checked it daily.',
  '…kept an airport arrival emoji as my most used one.',
  '…watched a plane take off and stayed until it was a dot.',
  '…planned the reunion outfit weeks before the flight landed.',
  '…rehearsed an entire pretend date in my head before asking.',
  '…imagined our wedding while they talked about the weather.',
  '…picked our future dog\'s name before date three.',
  '…practiced introducing someone as my partner to my mirror.',
  '…daydreamed through a lecture about a kiss that never happened.',
  '…imagined slow-dancing in the kitchen to no music at all.',
  '…written a diary entry that was ninety percent one person.',
  '…started a notes page titled "things to tell them later".',
  '…told my pet about a crush in complete sentences.',
  '…narrated a crush\'s imaginary reactions out loud while cooking.',
  '…paused a show to imagine texting them about it.',
  '…painted a sky because it reminded me of someone\'s eyes.',
  '…bought a book just because the main character had their name.',
  '…picked a favorite flower because it matched theirs.',
  '…kept a movie ticket stub until the ink faded.',
  '…pressed a flower from a first date inside a book.',
  '…kept a receipt from our first coffee together.',
  '…saved the napkin a phone number was written on.',
  '…kept a birthday card and reread it every year.',
  '…hidden a photo of us in my wallet for years.',
  '…written a love letter and never sent it.',
  '…written a poem so mushy it lives in a locked drawer.',
  '…printed and framed a blurry candid from our first trip.',
  '…made a scrapbook page for every date.',
  '…started a shared photo album named something cheesy.',
  '…burned a CD with one song on it, on repeat.',
  '…learned to play a song just to impress someone.',
  '…taken guitar lessons because of a breakup.',
  '…sung in the shower about someone, out loud.',
  '…sung karaoke while looking only at one person.',
  '…danced in the rain and blamed the weather.',
  '…slow-danced in a kitchen with the radio on low.',
  '…hummed our song on a crowded bus without noticing.',
  '…cried at a wedding before I even wanted one.',
  '…caught a bouquet and blushed like it meant something.',
  '…danced at a wedding with someone and wished it lasted longer.',
  '…practiced a signature with a different last name.',
  '…taken a quiz called "who is your celebrity soulmate" and hoped.',
  '…checked horoscope compatibility before a first date.',
  '…read our love compatibility out loud with a straight face.',
  '…asked a fortune teller about someone by name.',
  '…wished on a star and told no one the wish.',
  '…blown out birthday candles and spent the wish on a person.',
  '…picked petals off a daisy saying yes or no.',
  '…snapped a wishbone with someone and cheated.',
  '…thrown a coin in a fountain for love.',
  '…let a tarot reading decide whether to text first.',
  '…saved a fortune cookie fortune that mentioned love.',
  '…looked up the meaning of a flower before gifting it.',
  '…googled "how long should I wait to text back".',
  '…googled a date\'s favorite restaurant to book it first.',
  '…searched a crush\'s name at 2 a.m. and found an old interview.',
  '…stayed up until 3 a.m. reading about someone\'s hometown.',
  '…planned an entire trip around a famous couple\'s photo spot.',
  '…saved a restaurant for a special person for months.',
  '…practiced a proposal with a ring pop in the mirror.',
  '…tried on rings "just browsing" with a racing heart.',
  '…kept a ring box hidden in a sock drawer.',
  '…asked a jeweler questions I pretended were for a friend.',
  '…written a wedding speech for a day that hasn\'t happened.',
  '…cried watching a stranger\'s proposal video.',
  '…watched wedding videos just for the happy tears.',
  '…saved a wedding hashtag idea in my notes app.',
  '…chosen a honeymoon destination before a first anniversary.',
  '…practiced a first-dance move alone in the living room.',
  '…googled "cute date ideas near me" and saved five.',
  '…packed an overnight bag with a book just in case.',
  '…bought matching mugs for no reason.',
  '…worn matching shirts on purpose and dared someone to comment.',
  '…bought a couple\'s keychain and used only my half.',
  '…kept half of a friendship necklace for years.',
  '…shared an umbrella and sacrificed one whole shoulder.',
  '…lent a jacket and hoped it came back slowly.',
  '…worn a borrowed flannel and never given it back.',
  '…gifted a scarf as an excuse to meet again.',
  '…bought a gift three months before the occasion.',
  '…hidden a gift so well I found it after the holiday.',
  '…wrapped a present so badly it looked like a crime scene.',
  '…kept a gift secret for a month and nearly burst.',
  '…baked cookies and gave the whole batch to one person.',
  '…burned a first attempt at a romantic dinner.',
  '…made breakfast in bed and dropped the tray on the stairs.',
  '…memorized their coffee order before their birthday.',
  '…practiced a fancy dinner recipe on my family first.',
  '…arranged a heart on a pizza out of pepperoni.',
  '…piped a confession in icing across a cake.',
  '…picked out all the gummy bears for someone.',
  '…shared a milkshake with two straws on purpose.',
  '…ordered for someone else confidently and gotten it wrong.',
  '…stolen fries across the table as an excuse to lean closer.',
  '…paid the bill secretly and ran to the car.',
  '…planned a picnic and forgotten the blanket.',
  '…had ants crash a romantic picnic.',
  '…eaten dessert first because my date was nervous.',
  '…pretended the spicy food wasn\'t killing me.',
  '…suggested a walk just to stretch a date longer.',
  '…walked a date home the long way on purpose.',
  '…taken a wrong turn on a date and called it an adventure.',
  '…planned a date route by its dessert stops.',
  '…skipped the movie to talk in the parking lot.',
  '…fallen asleep on a shoulder during a film.',
  '…watched a scary movie just to hold a hand.',
  '…jumped at a horror scene and grabbed someone\'s arm.',
  '…laughed during the saddest scene because their face was funnier.',
  '…cried at a cartoon and gotten comforted about it.',
  '…shared earbuds, one side each, on a night bus.',
  '…built a fort out of couch cushions for date night.',
  '…swapped a fancy reservation for takeout and a blanket.',
  '…stargazed on a car roof and forgotten every constellation.',
  '…driven an hour to watch a sunset for ten minutes.',
  '…watched a sunrise after staying up all night talking.',
  '…drove up a hill just to watch the fog roll in.',
  '…stood in the cold just to finish a conversation.',
  '…walked in fresh snow to leave footprints side by side.',
  '…built a snowman that looked suspiciously like a crush.',
  '…ended a snowball fight with a truce and hot cocoa.',
  '…raked leaves into a heart shape.',
  '…jumped into a pile of leaves with someone.',
  '…gone apple picking mainly for the hayride.',
  '…carved a pumpkin portrait of someone, badly.',
  '…planned a couples costume that was ninety percent cardboard.',
  '…danced badly at a county fair and owned it.',
  '…won a stuffed animal and given it away that same night.',
  '…lost a ring toss because someone kept making me laugh.',
  '…ridden a ferris wheel to the top and stalled on purpose.',
  '…shared cotton candy and ended up sticky together.',
  '…kissed on a first date and pretended to be cool about it.',
  '…kissed under mistletoe that I definitely hung myself.',
  '…kissed in the rain like a movie scene.',
  '…had a first kiss interrupted by a phone call.',
  '…bumped noses during a first kiss.',
  '…laughed in the middle of a kiss and started over.',
  '…practiced a kiss on the back of my own hand.',
  '…kissed a celebrity poster as a teenager.',
  '…saved a kiss for the very last line of a letter.',
  '…blown a kiss through a car window in traffic.',
  '…held hands under a restaurant table.',
  '…squeezed a hand three times as a secret code.',
  '…traced letters on a palm during a boring movie.',
  '…kept a hand warm inside my coat pocket all the way home.',
  '…leaned on a shoulder and pretended to be tired.',
  '…fallen asleep on a train and woken up on a stranger\'s shoulder.',
  '…done the awkward pat-pat hug out of pure nerves.',
  '…gone in for a hug while they went for a handshake.',
  '…kept a hug three seconds longer than normal.',
  '…replayed a single compliment for an entire week.',
  '…called someone by an ex\'s name and wanted the floor to open.',
  '…accidentally used the dog\'s name instead of a pet name.',
  '…forgotten a date\'s name and had to wait for it.',
  '…said "you too" when the waiter told us to enjoy our meal.',
  '…over-tipped on a first date out of pure nerves.',
  '…worn new shoes on a date and regretted every step.',
  '…changed outfits five times before a simple coffee date.',
  '…ironed a shirt for a video call that showed only my head.',
  '…worn pajama bottoms to a serious video date.',
  '…brushed my hair in the middle of a date "just a second".',
  '…practiced an accent to impress and couldn\'t turn it off.',
  '…faked confidence for an entire evening and collapsed at home.',
  '…rehearsed a serious talk and then forgotten every word.',
  '…drafted an angry message and thanked myself at sunrise for deleting it.',
  '…cried on a call and been talked back to sleep.',
  '…had a first fight and made up over ice cream.',
  '…apologized with a hand-drawn card covered in doodles.',
  '…apologized in rhyme and been forgiven for the effort.',
  '…said sorry with a home-cooked meal and extra dessert.',
  '…been forgiven before I finished my apology speech.',
  '…told my best friend everything within an hour of a first date.',
  '…started a group chat just to plan one date.',
  '…recruited my sibling to report back on a crush\'s updates.',
  '…met someone\'s parents while wearing a food stain.',
  '…practiced a handshake with a partner\'s dad for a week.',
  '…won over a grandmother with dessert alone.',
  '…been interrogated by a best friend before a second date.',
  '…asked my mom how to fold napkins fancy for a date.',
  '…borrowed a friend\'s apartment to set up a surprise.',
  '…had friends chaperone a date from two tables away.',
  '…staged an "accidental" run-in after an hour of planning.',
  '…walked past a crush\'s café three times before going in.',
  '…ordered something unpronounceable and nodded like an expert.',
  '…faked being a regular at a coffee shop.',
  '…learned a chess opening overnight to seem smart.',
  '…joined a book club because someone mentioned it once.',
  '…taken a dance class just to have a story to tell.',
  '…adjusted my gym hours to someone else\'s, "coincidentally".',
  '…learned skateboard terms from a video the night before a date.',
  '…memorized a wine list before a dinner date.',
  '…guessed my own surprise party correctly and felt terrible.',
  '…planned a surprise and spilled the secret mid-sentence.',
  '…hidden a surprise gift in the one place they always look.',
  '…snuck into the kitchen at midnight for anniversary cake.',
  '…celebrated a monthly anniversary with a homemade coupon book.',
  '…invented a tiny holiday just to give one gift.',
  '…read a list of "ten things I love about you" out loud.',
  '…reread old messages out loud on an anniversary.',
  '…reenacted our first date down to the same table.',
  '…recreated our first photo on every anniversary.',
  '…kept a jar of written memories to open on hard days.',
  '…hidden love notes in a suitcase before a trip.',
  '…left my hair tie on their wrist as a tiny claim.',
  '…pressed a kiss into a palm and told them to save it for later.',
  '…texted "land safely" and refreshed a flight radar for an hour.',
  '…booked the next visit before the goodbye hug ended.',
  '…waited at arrivals with coffee and terrible jet lag.',
  '…surprised someone at baggage claim with their favorite snacks.',
  '…kept their favorite candy stocked for every arrival.',
  '…renamed my phone hotspot something only they would get.',
  '…said "I love you" first and panicked for a full minute.',
  '…said "I love you" as a joke and meant it.',
  '…ended a work call with "love you, bye" out of pure habit.',
  '…whispered "I love you" to a sleeping person and meant it.',
  '…written a message in the sand and let the tide keep it.',
  '…spelled "I love you" in sign language across a room.',
  '…caught myself humming a love song in a meeting.',
  '…chose the slowest checkout line to keep a conversation going.',
  '…made a heart with my arms from a departing train.',
  '…said "I love you" to my pet in front of a crush and meant the pet.',
  '…opened a shared savings account with a silly name.',
  '…hung a map with pins on every place we\'ve kissed.',
  '…bought a plant together and named it after our first trip.',
  '…adopted a tradition of pancakes every Sunday call.',
  '…ended a year on a call that rolled into the next one.',
];

/* ---------------- Never Have I Ever — 18+ ---------------- */
const NHIE_HOT = [
  '…kissed my partner somewhere unexpected in the house.', '…had a steamy dream about my partner this week.',
  '…skinny dipped with someone.', '…thought about my partner while at work… more than once.',
  '…ever been caught in the act.', '…worn something special just for my partner.',
  '…kissed someone\'s neck until they melted.', '…had a moment in a hot tub or pool.',
  '…given a massage that went somewhere else.', '…been on a date dressed up with no underwear jokes allowed… well.',
  '…licked whipped cream off someone.', '…kissed in the backseat of a car.',
  '…had my partner pick my outfit for a night.', '…fallen asleep tangled up with someone.',
  '…showered with a partner to "save water".', '…been covered in kisses until I laughed.',
  '…tried candlelight and slow music on purpose.', '…sent a text I would blush if my mom read.',
  '…held someone\'s hand under a table at dinner with a straight face.', '…kissed someone senseless at the door before they left.',
  '…planned an entire evening in the bedroom.', '…worn my partner\'s shirt and nothing else.',
  '…had a slow dance that turned into more.', '…hidden a love note somewhere cheeky.',
  '…fallen asleep in someone\'s arms mid-kiss.', '…been the little spoon and loved it.',
  '…wanted to skip dessert and go straight to bed.', '…surprised my partner after a shower.',
  '…counted down the hours until my partner got home.', '…smirked at an inside joke in public.',
  '…kept the lights on on purpose.', '…started something in the kitchen (cooking counts… barely).',
  '…lost track of time because of a kiss.', '…woken up at 3am just to be closer.',
  '…slow-danced in the living room with the lights off.',
  '…been kissed until I forgot what I was saying.',
  '…kissed someone against a front door as it closed.',
  '…let a kiss last through an entire song.',
  '…kissed someone\'s hand all the way up to the wrist.',
  '…been kissed on the neck and lost my train of thought forever.',
  '…kissed someone\'s knuckles across a restaurant table.',
  '…traded a dessert for a kiss at dinner.',
  '…been pulled closer by a belt loop.',
  '…dipped someone for a kiss and nearly dropped them.',
  '…kissed in an elevator and panicked at the ding.',
  '…kissed on a rooftop with the whole city humming below.',
  '…kissed at the very top of a ferris wheel.',
  '…kissed in the ocean shallows with salt on everything.',
  '…kissed under a waterfall and nearly slipped doing it.',
  '…shared a hot tub under falling snow, mist on our faces.',
  '…kissed someone\'s shoulder while they made coffee.',
  '…been kissed awake on a lazy Sunday.',
  '…kissed goodbye until the bus came and went twice.',
  '…kissed on a gondola lift with my heart in my throat.',
  '…given a massage with lotion warmed between my hands.',
  '…received a back massage that turned into falling asleep.',
  '…used a massage oil that smelled like a whole bakery.',
  '…traded massages instead of a movie night.',
  '…massaged shoulders under a blanket mid-flight.',
  '…had my hair washed slowly by someone else.',
  '…applied sunscreen to someone\'s back and taken the scenic route.',
  '…drawn slow circles on a wrist instead of finishing a conversation.',
  '…had my feet rubbed during a movie I pretended to watch.',
  '…been told to stop squirming during a massage.',
  '…worn lace under ordinary clothes and grinned all day.',
  '…bought lingerie and hidden it in a sock drawer for months.',
  '…modeled a new purchase with the lights turned low.',
  '…received a gift box with a bow and blushed for an hour.',
  '…worn silk just because it felt like a secret.',
  '…packed nice underwear for a trip and used none of it.',
  '…kept a borrowed tie for reasons I won\'t confess.',
  '…borrowed a flannel and forgotten to return it for a year.',
  '…left a flirty note in a packed suitcase.',
  '…worn heels to make dinner at home just because.',
  '…blown out candles and then fed someone by hand.',
  '…hand-fed a strawberry and made it a whole event.',
  '…shared a single dessert with two spoons on purpose.',
  '…ordered one dessert "to share" and defended it fiercely.',
  '…sipped from someone\'s glass while holding eye contact.',
  '…eaten a grape dangled from above.',
  '…shared an ice cream cone and blamed the sun for everything.',
  '…stolen the last bite and been chased around the kitchen.',
  '…kissed a smudge of chocolate off a chin.',
  '…drunk sparkling juice from the same bottle at midnight.',
  '…sneaked a kiss in a grocery aisle between the cereals.',
  '…kissed in a library and gotten shushed.',
  '…kissed in a photo booth and kept the strip.',
  '…kissed on a train through a tunnel, in the dark.',
  '…kissed on a ferry deck with wind everywhere.',
  '…kissed in a stairwell just because it was quiet.',
  '…kissed in the back row of a matinee.',
  '…kissed under an umbrella at a bus stop.',
  '…kissed at a crosswalk and gotten honked at.',
  '…kissed in the middle of a crowded dance floor.',
  '…been spun across a dance floor and dipped low.',
  '…danced with hands on hips in a crowded kitchen.',
  '…taught a slow dance to someone with two left feet.',
  '…danced in socks on hardwood until we fell over laughing.',
  '…danced with someone tall enough to rest a chin on my head.',
  '…danced to a song only one of us liked and both loved anyway.',
  '…swayed through the slowest song at a concert.',
  '…danced barefoot on a beach at midnight.',
  '…danced with a broom as a partner until the real one showed up.',
  '…kissed a hand after a spin and bowed dramatically.',
  '…been winked at across a party and walked straight into a wall.',
  '…played footsie through an entire dinner party.',
  '…whispered something that made someone choke on their drink.',
  '…passed a note that said "look at me and try not to smile".',
  '…kept a hand on someone\'s knee under a tablecloth.',
  '…traced a heart on a lower back while hugging goodbye.',
  '…whispered into an ear until someone shivered.',
  '…kissed the tip of a nose to win an argument.',
  '…nibbled an ear and caused a scene at brunch.',
  '…covered a face in lipstick marks like postage stamps.',
  '…had lipstick on my collar and owned it.',
  '…hidden a hickey with a scarf in the middle of summer.',
  '…worn a turtleneck in July and melted through dinner.',
  '…left a lipstick mark on a coffee mug and kept the mug forever.',
  '…left a pillowcase that smelled like cologne behind me.',
  '…kept a perfume-sprayed letter for hard days.',
  '…spritzed a scarf before a goodbye at the train station.',
  '…recognized someone by scent across a crowded room.',
  '…bought a perfume purely because of the compliment it earned.',
  '…used someone\'s shampoo and claimed the scent stayed all day.',
  '…been blindfolded and fed three mystery desserts.',
  '…used a scarf as a blindfold for a taste test.',
  '…guessed a lip balm flavor from a kiss alone.',
  '…been tickled until I begged for a timeout.',
  '…tickled someone until they laughed like a teakettle.',
  '…started a pillow fight and lost spectacularly.',
  '…wrestled over the remote and settled out of court.',
  '…been tackled onto a bed in a fit of giggles.',
  '…lost at thumb wars and paid in kisses.',
  '…kept a kiss scoreboard on the fridge whiteboard.',
  '…made a bet and paid up with a kiss.',
  '…won a bet and enforced the silly hat clause at brunch.',
  '…slow-danced to a song five times too fast for it.',
  '…been caught blushing and denied everything.',
  '…blushed at a compliment in front of my whole family.',
  '…gone red from a single raised eyebrow.',
  '…stammered through a compliment I wasn\'t ready for.',
  '…forgotten a word mid-flirt and invented one.',
  '…attempted a smooth line and tripped over it.',
  '…delivered a pickup line so bad it worked.',
  '…used a pickup line straight from a movie, badly.',
  '…been flustered just watching someone roll up their sleeves.',
  '…lost focus watching someone\'s hands make coffee.',
  '…been late because of a slow morning stretch in the doorway.',
  '…admired an outfit and forgotten to leave the house.',
  '…helped with a bow tie and made everyone late.',
  '…zipped up a dress and slowed down on purpose.',
  '…fixed a crooked collar and let my hands linger.',
  '…untangled a necklace clasp and taken longer than needed.',
  '…fastened an anklet and made a ceremony of it.',
  '…been kissed on top of the head while paying bills.',
  '…had glasses fog up from a kiss and worn it proudly.',
  '…kissed someone who wears glasses and learned nothing about angles.',
  '…been kissed upside down on a couch like in the movies.',
  '…kissed a forehead and been told it tickles.',
  '…kissed an eyelid mid-sentence to stop the rambling.',
  '…been nose-kissed during a video meeting and kept a straight face.',
  '…kissed someone silent during a tense board game.',
  '…lost a chess match on purpose because of a neck kiss.',
  '…kissed a bump better after a clumsy fall.',
  '…lit candles for ambiance and set off the smoke alarm.',
  '…queued a slow playlist and gotten the gym mix by accident.',
  '…dimmed the lights and tripped over the cat.',
  '…scattered rose petals and vacuumed them up the next day.',
  '…bought rose petals and found strays in the dryer for months.',
  '…hung fairy lights and called it ambiance.',
  '…planned a candlelit dinner and ordered pizza instead.',
  '…burned an entire candle down just talking.',
  '…dressed up for a video date knowing only my collarbones would show.',
  '…kept a video call running while getting ready for bed on both ends.',
  '…recorded a goodnight voice note nine times.',
  '…sent a voice note that made someone pull the car over.',
  '…written a steamy text and deleted it for a sweet one.',
  '…sent a flirty text to the group chat by mistake.',
  '…taken a photo showing only a shoulder and called it scandalous.',
  '…sent a photo of an outfit and demanded a rating out of ten.',
  '…been told to behave and behaved for exactly zero minutes.',
  '…kept a reunion countdown that got specific on day three.',
  '…written a list of visit plans that scandalized my notes app.',
  '…packed a date-night outfit at the very top of the suitcase.',
  '…hidden a gift under hotel pillows before a check-in.',
  '…booked a hotel room with a view for no reason at all.',
  '…been handed a hotel key card with a raised eyebrow.',
  '…hung a do-not-disturb sign through the breakfast hours.',
  '…slept until noon on a trip and blamed the curtains.',
  '…held hands through a five-course tasting menu.',
  '…shared a robe and still argued about the belt.',
  '…stolen the blankets and gotten retrieved like lost luggage.',
  '…woken up tangled beyond the laws of physics.',
  '…woken up with someone\'s hair in my mouth and said nothing.',
  '…been the little spoon and demanded it loudly.',
  '…fought over the cool side of the pillow and compromised by stacking.',
  '…had a staring contest end in laughter and a forehead touch.',
  '…whispered in the dark until 4 a.m. about nothing important.',
  '…counted freckles instead of sheep.',
  '…drawn on someone\'s arm with a fingertip until they slept.',
  '…listened to a heartbeat like a podcast.',
  '…had an arm fall asleep under someone and never moved it.',
  '…stayed perfectly still for an hour because someone slept on my sleeve.',
  '…woken up to a sleepy hug that said more than words.',
  '…been kissed on the temple while stirring soup.',
  '…been hugged from behind while brushing my teeth.',
  '…been kissed with spaghetti sauce on a cheek.',
  '…dried the dishes hip to hip on purpose.',
  '…been pulled off a ladder mid-chore for a kiss.',
  '…kept one matched sock pair from date night sacred in the drawer.',
  '…been caught slow-dancing with the vacuum cleaner.',
  '…made breakfast in an apron and a grin, allegedly.',
  '…fed someone batter off the spoon and guarded the bowl.',
  '…been kissed with flour on both cheeks.',
  '…started a flour fight before the cake was even baked.',
  '…poured a latte heart and been tipped in kisses.',
  '…served breakfast in bed and eaten most of it myself.',
  '…delivered coffee to someone singing in the shower.',
  '…drew a heart on a fogged windshield before it cleared.',
  '…strutted down a hallway in a towel like it was a runway.',
  '…locked us both out of the bathroom and blamed the steam.',
  '…shared a sauna and lasted four minutes.',
  '…sat in a hot spring with snowflakes landing on our heads.',
  '…shivered after a warm pool and gotten wrapped in two towels.',
  '…been carried over a threshold and dropped, gently, once.',
  '…carried a partner over a threshold and pulled a muscle doing it.',
  '…given a piggyback ride down a hotel corridor.',
  '…ridden on someone\'s back through an airport like royalty.',
  '…been spun until dizzy and kissed on the landing.',
  '…held on tight on a scooter downhill and screamed happily.',
  '…been dipped into a pool and come up laughing.',
  '…jumped into a pool fully dressed to win an argument.',
  '…been pushed into a pool and pulled the pusher in after.',
  '…floated on someone\'s back in a calm lake until sunset.',
  '…built a sandcastle with a tower named after us.',
  '…found sand in my bag for weeks after one beach day.',
  '…kissed at a lighthouse and gotten photobombed by a seagull.',
  '…sung to someone off-key on a porch swing.',
  '…fallen asleep in a hammock in a tangle of two.',
  '…shared a hammock and learned gravity\'s lesson.',
  '…watched stars from a trampoline until the sprinklers came on.',
  '…caught fireflies for luck and released them for kisses.',
  '…huddled under one coat at a cold ballgame.',
  '…been pulled into a photo and kissed in the very last frame.',
  '…kept a photo strip as a bookmark.',
  '…staged a fake proposal photo that fooled both moms.',
  '…booked a couple\'s photoshoot and laughed through every frame.',
  '…had a kiss caught in slow motion.',
  '…recorded a silly couple\'s dance and kept it private forever.',
  '…laughed at old flirty texts with tears in my eyes.',
  '…found a first "good morning" text and melted all over again.',
  '…screenshotted the very first "I miss you" exchange.',
  '…worn one perfume every anniversary on purpose.',
  '…renewed a tradition of dessert before dinner every year.',
  '…played twenty questions where every lie cost a kiss.',
  '…played truth or dare with a guest list of two.',
  '…chosen "dare" three times in a row and survived.',
  '…been dared to do a dramatic reading of an old text.',
  '…played a board game where a kiss bought a skip.',
  '…invented a card game where the rules kept changing.',
  '…lost a card game and been smug about the prize anyway.',
  '…won a card game and demanded the forfeit immediately.',
  '…turned a movie night into charades halftime.',
  '…paused a film for a very important debate about a kiss.',
  '…been serenaded terribly and loved it completely.',
  '…hummed a lullaby and gotten one hummed back.',
  '…pretended to still be asleep to hear one more song.',
  '…been assigned the harmony part in kitchen duets.',
  '…had a song dedicated on the radio, corny and perfect.',
  '…danced at a wedding until the band packed up.',
  '…led a conga line of two.',
  '…performed a car duet with full choreography at red lights.',
  '…kept the radio on static just for the dancing excuse.',
  '…been dipped so low my hair touched the floor.',
  '…matched Halloween costumes and answered to "those two" all night.',
  '…stolen a kiss through a masquerade mask.',
  '…kept a masquerade mask on the wall as a trophy.',
  '…been crowned prom royalty and made it a whole thing.',
  '…slipped out to a balcony and come back different.',
  '…been caught on a porch by headlights and waved anyway.',
  '…said goodnight at the door for an entire hour.',
  '…backed down a front walk waving until the very end.',
  '…texted from the driveway five minutes after leaving.',
  '…driven around the block an extra time to finish a song.',
  '…kept a date going past closing time at a diner.',
  '…been the last two in a coffee shop and earned the glares.',
  '…closed down a bowling alley on a first date.',
  '…played air hockey until the arcade closed.',
  '…won a stuffed bear and named it after the night.',
  '…shared a pretzel the size of a steering wheel.',
  '…gotten lost after midnight and found the perfect diner.',
  '…driven to see a "quick sunrise" that took three hours.',
  '…pulled over to watch a storm roll in.',
  '…run through a fountain to beat the rain and lost.',
  '…huddled under one blanket at a freezing stadium.',
  '…been on the kiss cam and hammed it up for a whole stadium.',
  '…won a raffle for two and brought my favorite person.',
  '…sung the encore from the parking lot on the radio.',
  '…kept a concert wristband on until it fell apart.',
  '…traded festival bracelets and never taken mine off.',
  '…shared a poncho in a downpour and danced anyway.',
  '…lost each other in a crowd and reunited by whistle.',
  '…carried someone on my shoulders to see the stage.',
  '…come home from a festival with glitter that never left.',
  '…kept a sparkler burning for an entire wish.',
  '…kissed through sparkler smoke at midnight.',
  '…been kissed at midnight while everyone cheered.',
  '…watched fireworks from the bed of a truck, shoulder to shoulder.',
  '…given a toast that made the room cry and blush.',
  '…smashed cake into a face at a wedding and been forgiven.',
  '…caught the garter and turned crimson.',
  '…danced with a grandmother and been thoroughly out-danced.',
  '…sneaked wedding cake at 2 a.m. in formalwear.',
  '…slept in formalwear because the night was too good to end.',
  '…planned a whole date around one word in a new language.',
  '…learned a pet name in another language and overused it.',
  '…flirted through a translation app and it worked.',
  '…flirted in the wrong language on purpose for a laugh.',
  '…memorized "you\'re beautiful" in three languages.',
  '…taught a partner my grandmother\'s lullaby.',
  '…kept a phrasebook with hearts in the margins.',
  '…practiced a name with the right accent until it sang.',
  '…flirted across a market stall in broken grammar.',
  '…mispronounced a love note and been laughed with, not at.',
  '…planned a future with someone across an ocean.',
  '…kept two toothbrushes ready months before a visit.',
  '…assigned a pillow a name before a first visit.',
  '…cleared half a closet for someone across the world.',
  '…flown overnight just to make someone breakfast.',
  '…memorized a flight number like a phone number.',
  '…stayed up all night to match someone\'s sunrise.',
  '…scheduled a lunch date across a twelve-hour difference.',
  '…kept a shared calendar with a nightly block named "our call".',
  '…sent a good-morning rooster impression on repeat.',
  '…planned a reunion itinerary and left one page intentionally blank.',
  '…looked at the same moon on a call and called it a date.',
  '…mailed a hoodie before winter with a hug pre-loaded.',
  '…kept a jar labeled "next visit\'s ice cream fund".',
  '…lingered at a gate until the final call, twice.',
];

/* ---------------- Spicy Would You Rather (18+) ---------------- */
const WYR_HOT = [
  ['Slow, lingering kisses for an hour', 'A surprise kiss that takes my breath away'],
  ['A candlelit bubble bath for two', 'A midnight skinny dip'],
  ['A full-body massage with oil', 'Being kissed from head to toe'],
  ['Whispered secrets under the sheets', 'Loud laughter that turns into more'],
  ['A weekend hotel with no plans', 'A night in with nothing but each other'],
  ['I plan the seduction', 'You plan the seduction'],
  ['Morning kisses before coffee', 'Midnight kisses after wine'],
  ['A slow dance in candlelight', 'A steamy shower duet'],
  ['Blindfolded taste tests', 'Feather-light tickle fights'],
  ['Love bites or soft traces?', 'Gentle scratches or tender holds?'],
  ['Being pinned softly against the wall', 'Being lifted off my feet'],
  ['A striptease just for me', 'A lap dance just for me'],
  ['Sexting all day then exploding at night', 'Total radio silence then pure surprise'],
  ['Ice cubes or warm candle wax (safely!)', 'Silk blindfold or fluffy handcuffs'],
  ['Kiss me in public, daringly', 'Kiss me somewhere we could get caught… almost'],
  ['I wear your shirt all day', 'You wear my perfume all night'],
  ['Whisper my name', 'Moan my name'],
  ['Breakfast served in bed, wearing only an apron', 'Dinner slow-cooked with zero clothes plan'],
  ['A kiss that never stops', 'A hug that becomes a kiss'],
  ['Netflix or chill?', 'Chill then Netflix?'],
  ['Take a couples\' dance class', 'Take a couples\' massage class'],
  ['A dare I can\'t refuse', 'A truth I can\'t hide'],
  ['Stargazing on a blanket', 'Stargazing with no blanket… need body heat'],
  ['Hot tub with champagne', 'Sauna with whispered confessions'],
  ['I surprise you at work', 'You surprise me at home'],
  ['Slow build-up all evening', 'Spontaneous spark right now'],
  ['Your lips on my neck', 'Your hands in my hair'],
  ['Falling asleep tangled together', 'Waking up tangled together'],
  ['A rain-soaked kiss outside', 'A fireside cuddle inside'],
  ['I whisper what I want', 'I show you what I want'],
  ['Slow, deep kisses for an hour', 'A hundred quick, teasing kisses'],
  ['Whisper my name against my neck', 'Moan my name in the dark'],
  ['I plan the whole seduction', 'You surrender to my plan'],
  ['Slow dancing in candlelight', 'Slow dancing in the rain'],
  ['A kiss hello that lingers', 'A kiss goodbye that lingers longer'],
  ['Kiss me in the rain', 'Kiss me under the fireworks'],
  ['Kiss my fingertips, one by one', 'Kiss the curve of my shoulder'],
  ['A surprise kiss from behind', 'A slow lean-in I can see coming'],
  ['Butterfly kisses on my eyelids', 'Feather kisses on my collarbone'],
  ['First kiss of the night', 'Last kiss before sleep'],
  ['My hands in your hair', 'Your hands tracing my spine'],
  ['A massage that melts me', 'A tickle fight that wakes me'],
  ['Holding hands under the table', 'Feet tangled under the blanket'],
  ['Your fingertips on my wrist', 'My head on your heartbeat'],
  ['A hug from behind at the stove', 'A twirl in the kitchen doorway'],
  ['Tracing letters on my back till I guess the word', 'Drawing circles on my palm till I fall asleep'],
  ['Warm hands on cold shoulders', 'Cold fingers slipping into my sleeve'],
  ['Your thumb tracing my knuckles', 'My name traced on my knee'],
  ['A slow dance with no music', 'A fast song that never ends'],
  ['Fingers brushing while passing a cup', 'Hands catching on the way down'],
  ['Candlelight and rain on the window', 'Moonlight and waves outside'],
  ['Fairy lights and a shared blanket', 'Fireplace and one glass of wine'],
  ['Thunderstorm outside, us inside', 'Snowstorm outside, fireplace inside'],
  ['A hotel room with a city view', 'A cabin with no wifi'],
  ['Silk sheets and slow music', 'Old t-shirt and your favorite show'],
  ['Sunset on a rooftop', 'Sunrise on a balcony'],
  ['A hammock built for one, shared', 'A bed built for two, both sides warm'],
  ['Christmas lights in July', 'Candles on a Tuesday afternoon'],
  ['Rain sounds and your heartbeat', 'Ocean sounds and your breathing'],
  ['A room lit only by the TV', 'A room lit only by candles'],
  ['I plan the whole evening', 'You plan every surprise'],
  ['I take the lead tonight', 'You take the lead tonight'],
  ['I whisper the dare', 'You dare me first'],
  ['I pick what you wear', 'You pick what I wear'],
  ['I get teased all night', 'I do the teasing all night'],
  ['I say when to stop', 'You say when to slow down'],
  ['I pick the movie, you pick the mood', 'You pick the movie, I pick the seating'],
  ['You pull me closer first', 'I pull you closer first'],
  ['I write the rules tonight', 'We break the rules tonight'],
  ['Me saying please', 'You saying please'],
  ['A lazy morning in bed', 'A stolen hour at midnight'],
  ['Slow morning kisses before coffee', 'Sleepy kisses after midnight'],
  ['An hour that feels like a minute', 'A minute that feels like an hour'],
  ['Start the night early, end it late', 'Start late, never end it'],
  ['A Tuesday surprise', 'A Saturday that lasts all weekend'],
  ['Now, right this second', 'Anticipation all week first'],
  ['A quick kiss before you leave', 'A long goodbye at the door'],
  ['Late-night call that never ends', 'Early call with sleepy voices'],
  ['Three a.m. confessions', 'Noon-in-bed confessions'],
  ['A whole day in bed', 'A whole night under the stars'],
  ['Kissed against the kitchen counter', 'Pinned playfully to the hallway wall'],
  ['A slow dance in the kitchen', 'A stolen kiss in the stairwell'],
  ['Beach towel at midnight', 'Hotel bed at noon'],
  ['Backseat of a taxi, holding hands', 'Front seat of your car, engine still warm'],
  ['An elevator that stops between floors', 'A stairwell that echoes'],
  ['Rooftop under one jacket', 'Blanket fort with one flashlight'],
  ['Hot tub under cold stars', 'Warm rain on a summer porch'],
  ['Bookstore aisle, brushing fingers', 'Coffee shop corner, knees touching'],
  ['Train window, city lights, your shoulder', 'Airport gate, long layover, your hand'],
  ['A dance floor with everyone watching', 'An empty room with no one watching'],
  ['A voice note of my name', 'A handwritten note under my pillow'],
  ['Sixty seconds of compliments', 'Sixty seconds of whispers'],
  ['Tell me what you\'re thinking', 'Guess what I\'m thinking'],
  ['Me reading to you in bed', 'You reading over my shoulder'],
  ['A whisper so close it tickles', 'A laugh so warm it melts me'],
  ['Say it in a text', 'Say it against my lips'],
  ['Good morning text that ruins my focus', 'Good night call that steals my sleep'],
  ['Tell me your favorite memory of us', 'Invent our next one out loud'],
  ['I dare you to say it first', 'I\'ll say it first'],
  ['Pet names in public', 'Real names in a whisper'],
  ['Teasing all night, reward at dawn', 'All the rewards, none of the waiting'],
  ['An almost-kiss that lingers', 'A kiss that never quite stops'],
  ['I know you\'re staring', 'You catch me staring'],
  ['Seven days of anticipation', 'Seven seconds of surprise'],
  ['A dare I can\'t refuse', 'A truth I can\'t dodge'],
  ['I get one wish', 'I get three tries'],
  ['Slow build all evening', 'Skip to the good part'],
  ['You make me ask twice', 'You never make me ask'],
  ['Almost touching on the video call', 'Actually touching, finally, at the airport'],
  ['I count the days', 'You make me lose count'],
  ['Blindfolded and guessing', 'Eyes open the whole time'],
  ['An ice cube traced on my palm', 'A warm towel from the dryer'],
  ['Your favorite cologne on my pillow', 'My perfume on your collar'],
  ['Chocolate shared from the same square', 'Wine shared from the same glass'],
  ['A song that means us on repeat', 'A new song to mean us'],
  ['Fresh sheets, warm from the dryer', 'Your shirt, warm from you'],
  ['Strawberries or chocolate?', 'Whipped cream or honey?'],
  ['The smell of rain and your jacket', 'The smell of coffee and your morning voice'],
  ['A kiss that tastes like dessert', 'A whisper that tastes like trouble'],
  ['Wrapped in velvet', 'Wrapped in your arms'],
  ['I dare you to kiss me slow', 'I dare you not to kiss me at all'],
  ['I dare you to whisper a secret', 'I dare you to act it out'],
  ['One dare, no limits', 'One truth, no lying'],
  ['I dare you to hold eye contact', 'I dare you to look away first'],
  ['I dare you to dance for me', 'I dare you to serenade me'],
  ['I dare you to say what you felt first', 'I dare you to show me instead'],
  ['I dare you to steal a kiss', 'I dare you to let me steal one'],
  ['I dare you to be gentle', 'I dare you to be brave'],
  ['I dare you to write it down', 'I dare you to whisper it twice'],
  ['I dare you to start it', 'I dare you to finish it'],
  ['Your button-down and nothing else', 'My silk robe and your cologne'],
  ['Undressing me slowly', 'Redressing me so we can go out again'],
  ['Zip up my dress', 'Unzip my dress'],
  ['Your tie as a blindfold', 'Your jacket as my blanket'],
  ['Socks on and sweaters off', 'Coats on and cold noses'],
  ['Steal my hoodie', 'Give me yours to keep'],
  ['Me in your oversized shirt', 'You in my too-small sweater'],
  ['Getting ready together in one mirror', 'Surprising each other at the door'],
  ['Heels off at midnight', 'Jacket on the floor by ten'],
  ['Hair still wet from the shower', 'Makeup still on from the party'],
  ['A bubble bath built for two', 'A shower that runs out of hot water'],
  ['Water fight in the ocean', 'Rainstorm sprint to the car'],
  ['Night swimming under the stars', 'Sunrise swim before the world wakes'],
  ['Shared umbrella, one dry shoulder', 'Two umbrellas, running to meet'],
  ['Hot spring in falling snow', 'Warm rain on a summer storm'],
  ['Steam on the mirror, your initials', 'Fog on the window, our song'],
  ['Your towel on the floor', 'My robe on the chair'],
  ['A bath with extra bubbles', 'A bath with extra you'],
  ['Shower before breakfast', 'Shower long past breakfast'],
  ['The last warm towel', 'The first warm hug'],
  ['Feeding me grapes, one by one', 'Tasting wine from my lips'],
  ['Dessert first', 'Dessert only'],
  ['Breakfast in bed', 'Midnight snacks in the blanket fort'],
  ['Sharing one milkshake, two straws', 'Sharing one plate, no forks'],
  ['Chocolate on your thumb', 'Sugar on my lips'],
  ['Cooking together, flour everywhere', 'Ordering in, blankets everywhere'],
  ['Ice cream straight from the tub', 'Cherries straight from the bowl'],
  ['A picnic where the basket is forgotten', 'A dinner reservation we never make'],
  ['Kisses that taste like coffee', 'Whispers that taste like wine'],
  ['The last bite, offered', 'The first bite, stolen'],
  ['Falling asleep mid-sentence', 'Waking up mid-kiss'],
  ['Your arm as my pillow', 'My shoulder as your headrest'],
  ['Sleepy morning voice', 'Midnight low voice'],
  ['Staying up to watch the sunrise', 'Sleeping straight through to noon'],
  ['Legs tangled all night', 'Back to back, feet still touching'],
  ['You steal all the blankets', 'I steal all the closeness'],
  ['Snooze button, ten more minutes', 'Alarm off, ten more hours'],
  ['Morning breath, still kissing', 'Bed head, still laughing'],
  ['Pancakes in pajamas', 'Champagne in bathrobes'],
  ['Your cold feet finding my warm legs', 'My cold hands finding your warm neck'],
  ['Kiss the camera goodnight', 'Fall asleep with the call still on'],
  ['A care package that smells like me', 'A playlist that sounds like us'],
  ['Countdown to the airport', 'Countdown to the doorstep'],
  ['Voice memo lullaby', 'Video message surprise'],
  ['Typing I miss you first', 'Typing I miss you more'],
  ['Watching the same movie on call', 'Falling asleep to each other\'s breathing'],
  ['A letter I can hold', 'A text I can reread instantly'],
  ['One week together every month', 'One month together every year'],
  ['Screenshots of your smile', 'Voice notes of your laugh'],
  ['Meeting halfway, always', 'Rotating visits, never boring'],
  ['Loser grants one wish', 'Winner takes the crown'],
  ['Strip trivia on video call', 'Slow-dance charades over the phone'],
  ['One question each, all night', 'No questions, all guesses'],
  ['I win, you spoil me', 'You win, I spoil you'],
  ['Board games and betrayal kisses', 'Card games and wager kisses'],
  ['Truth or dare, only truths', 'Truth or dare, only dares'],
  ['I guess your tell', 'You bluff me completely'],
  ['Stakes: the last dance', 'Stakes: the whole weekend'],
  ['Losing on purpose to you', 'Winning and gloating in your lap'],
  ['A game neither of us finishes', 'A rematch every night'],
  ['First snow, first kiss', 'Last firefly, last dance'],
  ['Sweater weather and shared sleeves', 'Summer nights and shared shade'],
  ['Pumpkin patch, your hand in mine', 'Christmas market, my hand in yours'],
  ['Leaves crunching on one blanket walk', 'Waves crashing on one moonlit walk'],
  ['New Year\'s kiss at midnight', 'Birthday kiss at 12:01'],
  ['Valentine\'s reservations we skip', 'Anniversary gifts we forget to open'],
  ['Spring rain, one borrowed jacket', 'Autumn wind, one shared scarf'],
  ['Building the snowman', 'Building the fire'],
  ['Summer thunderstorm, windows open', 'Winter blizzard, curtains closed'],
  ['Oranges in your stocking', 'Kisses in every pocket'],
  ['Road trip with no destination', 'Flight with no return date'],
  ['Getting lost in a new city', 'Getting found in the hotel lobby'],
  ['Sleeping in the car to catch the sunrise', 'Waking in a tent to hear the rain'],
  ['Your hand on the gearshift', 'Your head on my shoulder at 80 mph'],
  ['Map in my lap, your hand on my knee', 'Map on the floor, wherever the day goes'],
  ['Stranded by the storm, delighted', 'Detoured by fate, grateful'],
  ['A mountaintop at dawn', 'A hidden cove at noon'],
  ['Passport stamps in pairs', 'Postcards sent from the same room'],
  ['First class with champagne', 'Roadside diner with milkshakes'],
  ['Home is wherever you are', 'Home is the place we build'],
  ['A kiss on the neck that lingers', 'A whisper in the ear that shivers'],
  ['Slow hands and slower intentions', 'Fast heartbeat and faster breathing'],
  ['Being pulled closer', 'Being held still'],
  ['My back against the door', 'Your hand against the wall'],
  ['Carried to the bedroom', 'Walking there slowly, hand in hand'],
  ['One candle, two shadows', 'No lights, all senses'],
  ['Kiss me like it\'s the last time', 'Kiss me like it\'s the first time'],
  ['Your breath on my collarbone', 'My whisper on your jaw'],
  ['The room spinning from your kiss', 'The world stopping for your touch'],
  ['Counting your freckles with my lips', 'Memorizing your smile with my hands'],
  ['I trace your tattoo', 'You find my ticklish spot'],
  ['A look across the party', 'A hand under the table'],
  ['Texting come over right now', 'Already knocking at the door'],
  ['A lipstick confession on your collar', 'A perfume promise on your shirt'],
  ['I pretend not to notice you staring', 'You pretend you weren\'t'],
  ['Teasing in public, innocent faces', 'Scolding in private, guilty smiles'],
  ['A wink from across the room', 'A whistle from down the hall'],
  ['Slow motion in the doorway', 'Sudden blur against the wall'],
  ['You bite your lip', 'I lose my train of thought'],
  ['You stretch in the morning', 'I forget every word I know'],
  ['Being commanded gently', 'Being obeyed completely'],
  ['I say stop, you slow down', 'I say again, you smile'],
  ['You pin my hands softly', 'I wrap my arms tighter'],
  ['Your hand at the small of my back', 'Your fingers laced through mine'],
  ['Being teased until I beg', 'Being spoiled until I melt'],
  ['I melt for your commands', 'You crumble for my pout'],
  ['You decide tonight', 'I decide tomorrow'],
  ['The boss in the streets', 'The softie at the door'],
  ['Carried over the threshold', 'Pulled over the arm of the couch'],
  ['Commanding whisper', 'Obeying smile'],
  ['Slow song, no space between us', 'Fast song, no feet on the ground'],
  ['Dancing in the dark', 'Kissing in the spotlight'],
  ['Your humming as my lullaby', 'My heartbeat as your metronome'],
  ['Radio static and open windows', 'Silence and close whispers'],
  ['Dancing on the balcony, barefoot', 'Kissing in the kitchen, mid-recipe'],
  ['The song that was playing when we met', 'The song we\'ll dance to at our wedding'],
  ['Headphones shared, one ear each', 'Speakers loud, doors locked'],
  ['Vinyl crackle and candle glow', 'Bluetooth and phone flashlight'],
  ['Your terrible singing, all mine', 'Your perfect whistle, just for me'],
  ['A concert for two in the living room', 'A crowd of one, you watching me sing'],
  ['One wish, used tonight', 'One wish, saved for later'],
  ['A love letter read aloud', 'A voicemail saved forever'],
  ['Ten-year plan whispered', 'Tonight\'s plan improvised'],
  ['Your bucket list with my name in it', 'My bucket list in your handwriting'],
  ['A promise sealed with a kiss', 'A secret sealed with a smile'],
  ['Our song rewritten for us', 'Our story retold, same ending'],
  ['A jar of folded memories', 'A box of ticket stubs'],
  ['P.S. at the end of every letter', 'P.S. in the middle of every kiss'],
  ['Writing vows we haven\'t planned', 'Keeping promises we already made'],
  ['A ring in my pocket', 'A ring in your soup'],
  ['Pillow fight that ends in feathers', 'Water fight that ends in towels'],
  ['Chase me around the couch', 'Catch me at the doorway'],
  ['Stealing the last slice', 'Feeding me the last slice'],
  ['Your cold toes, my squeal', 'My cold toes, your yelp'],
  ['Popcorn thrown during the movie', 'Popcorn abandoned during the kiss scene'],
  ['Falling asleep during the movie', 'Missing the ending entirely'],
  ['Ping-pong rematch, kisses on the line', 'Bowling rematch, bragging rights at stake'],
  ['Nerf war with no truce', 'Water balloon war with instant truce'],
  ['Trivia night, losing together', 'Karaoke night, winning alone'],
  ['Karaoke duet, terrible harmony', 'Silent disco, perfect harmony'],
  ['A kiss that starts an argument', 'An argument that ends in a kiss'],
  ['Slow is the whole point', 'Fast is the whole point'],
  ['Every light on', 'Every curtain drawn'],
  ['Goosebumps on purpose', 'Shivers by accident'],
  ['Your heartbeat under my ear', 'My pulse under your lips'],
  ['Breathing in unison', 'Losing count of everything'],
  ['The pause before the kiss', 'The sigh after it'],
  ['Legs tangled, no escape', 'Loose embrace, no escape either'],
  ['Fingers interlaced, tight', 'Arms wrapped, tighter'],
  ['The word yes', 'The word again'],
  ['Being chosen every morning', 'Being chosen every night'],
  ['Love that feels like coming home', 'Love that feels like an adventure'],
  ['Forever starting tonight', 'Tonight lasting forever'],
  ['Your name on my lips', 'My name in your handwriting'],
  ['Growing old but never up', 'Staying young but always home'],
  ['The best first date ever', 'The best ordinary Tuesday'],
  ['Known completely, loved anyway', 'Seen briefly, wanted instantly'],
  ['Your hand when I\'m scared', 'My hand when you\'re brave'],
  ['A love like a steady flame', 'A love like a lightning strike'],
  ['All of my mornings', 'Every one of your midnights'],
  ['Kisses mapped like constellations', 'Touches counted like lucky stars'],
  ['A weekend we never leave the bed', 'A week we never stop exploring'],
  ['Perfume on the letter you mailed', 'Cologne in the box you sent'],
  ['Wearing your watch all week', 'Keeping my ribbon on your mirror'],
  ['Slow dancing to the fridge hum', 'Waltzing to the washing machine'],
  ['A kiss per folded towel', 'A kiss per washed dish'],
  ['Sunrise alarms with your voice', 'Sunset calls with your face'],
  ['I fall asleep first, you tuck me in', 'You fall asleep first, I stay and listen'],
  ['Matching pajamas, mandatory', 'Mismatched socks, mandatory'],
  ['Your laugh through the speaker', 'Your smile through the screen'],
  ['Frozen pizza, candlelit', 'Fancy dinner, barefoot'],
  ['The playlist you made me', 'The voicemail you kept'],
  ['Arguing about the thermostat', 'Agreeing on everything that matters'],
  ['Stealing your fries, offered', 'Stealing your hoodie, unbothered'],
  ['Your arm asleep under my head', 'My leg asleep over your lap'],
  ['Morning voice, five more minutes', 'Evening voice, one more chapter'],
  ['You memorize my coffee order', 'I memorize your everything'],
  ['Rain checks on everything else', 'No rain checks on us'],
  ['Falling for you again daily', 'Loving you deeper hourly'],
  ['The goodnight call that runs three hours', 'The goodnight text that starts a novel'],
  ['A hotel robe you can\'t pack', 'A memory you can\'t unpack'],
  ['Dancing down the grocery aisle', 'Kissing by the freezer aisle'],
  ['Your hands warming my fingers', 'My fingers tracing your palms'],
  ['The seat warmer on, for me', 'The playlist up, for us'],
  ['Snacks hidden for the movie', 'Snacks finished before the movie'],
  ['A museum we whisper through', 'A park we nap through'],
  ['The last cookie split in half', 'The last cookie fought over playfully'],
  ['Your keys on my counter', 'My toothbrush at your place'],
  ['A bubble bath and a locked door', 'A long drive and an open window'],
  ['Whispers during the scary movie', 'Covered eyes during the scary part'],
  ['Your heartbeat speeding my pace', 'My calm slowing yours'],
  ['A kiss that answers everything', 'A question that begs a kiss'],
  ['Sunday crosswords in bed', 'Saturday pancakes in pajamas'],
  ['The umbrella tilted your way', 'The jacket draped over both of us'],
  ['Midnight drive with no radio', 'Dawn walk with no phones'],
  ['The armchair by the window, shared', 'The floor cushions by the fire, shared'],
  ['A dance card with one name', 'A phone with one favorite'],
  ['The front seat, your jacket', 'The back seat, stargazing'],
  ['Sleeping on your shoulder on the train', 'Waking with your coat over me'],
  ['The goodbye that takes an hour', 'The hello that takes a second'],
  ['A kiss that means hello', 'A kiss that means don\'t go'],
  ['Your shirt as my pillowcase', 'My scent on your sweater'],
  ['Slow morning, no clocks', 'Late night, no lights'],
  ['Whatever you want, always', 'Whatever I want, right now'],
  ['A love written in pencil, then ink', 'A love carved in stone, then kissed'],
];

/* ---------------- registration ---------------- */

makeDuoGame({
  id: 'nhie', name: 'Never Have I Ever', tag: 'Confess, giggle, get closer', icon: '🙈', section: 'classic',
  bank: NHIE_STD,
  promptOf: (q) => q,
  options: [
    { v: 'never', label: 'Never have I ever', emoji: '🙅' },
    { v: 'have', label: 'Oh I have', emoji: '😏' },
  ],
  endEmoji: '🙈',
});

makeDuoGame({
  id: 'nhie18', name: 'Never Have I Ever', tag: 'The after-dark edition', icon: '🌶️', section: 'adult',
  bank: NHIE_HOT,
  promptOf: (q) => q,
  options: [
    { v: 'never', label: 'Never have I ever', emoji: '🙅' },
    { v: 'have', label: 'Oh, I have', emoji: '😏' },
  ],
  endEmoji: '🌶️',
});

makeDuoGame({
  id: 'wyr', name: 'Spicy Would You Rather', tag: 'Two tempting scenarios — pick in secret', icon: '🍑', section: 'adult',
  bank: WYR_HOT,
  promptOf: (pair) => `Would you rather… ${pair[0]}  or  ${pair[1]}?`,
  options: [
    { v: 'a', label: (item) => item[0], emoji: '🅰️' },
    { v: 'b', label: (item) => item[1], emoji: '🅱️' },
  ],
  matchCheck: (a, b) => a === b,
  answerText: (v, q) => (v === 'a' ? q[0] : q[1]),
  endEmoji: '🍑',
});
